#!/bin/bash

export ESCIDOCNG_BACKEND_HOME=/data/escidocng/backend
export ESCIDOCNG_BACKEND_NAME=escidocng-backend
export ESCIDOCNG_FRONTEND_HOME=/data/escidocng/frontend
export ESCIDOCNG_FRONTEND_NAME=escidocng-frontend

#Names of startscripts. Has to be located in ESCIDOCNG_BACKEND_HOME + ESCIDOCNG_FRONTEND_HOME
export ESCIDOCNG_BACKEND_STARTSCRIPT=backend.start
export ESCIDOCNG_FRONTEND_STARTSCRIPT=frontend.start

export ESCIDOCNG_USER=admin

function start {
    if pkill -0 -f $ESCIDOCNG_BACKEND_NAME.jar > /dev/null 2>&1
    then
    	pkill -f $ESCIDOCNG_BACKEND_NAME.jar > /dev/null 2>&1
    fi
    echo "Starting server..."
    cd $ESCIDOCNG_BACKEND_HOME
    sudo -u $ESCIDOCNG_USER ./$ESCIDOCNG_BACKEND_STARTSCRIPT
    
    sleep 30
    
    if pkill -0 -f $ESCIDOCNG_FRONTEND_NAME.jar > /dev/null 2>&1
    then
        pkill -f $ESCIDOCNG_FRONTEND_NAME.jar > /dev/null 2>&1
    fi
    echo "Starting frontend..."
    cd $ESCIDOCNG_FRONTEND_HOME
    sudo -u $ESCIDOCNG_USER ./$ESCIDOCNG_FRONTEND_STARTSCRIPT 
}

function stop {
    if ! pkill -0 -f $ESCIDOCNG_BACKEND_NAME.jar > /dev/null 2>&1
    then
        echo "Service [$ESCIDOCNG_BACKEND_NAME] is not running. Ignoring shutdown request."
    else
    	pkill -f $ESCIDOCNG_BACKEND_NAME.jar > /dev/null 2>&1
    fi

    if ! pkill -0 -f $ESCIDOCNG_FRONTEND_NAME.jar > /dev/null 2>&1
    then
        echo "Service [$ESCIDOCNG_FRONTEND_NAME] is not running. Ignoring shutdown request."
    else
    	pkill -f $ESCIDOCNG_FRONTEND_NAME.jar > /dev/null 2>&1
    fi
    
}

case $1 in
start)
    start
;;
stop)
    stop
;;
restart)
    stop
    start
;;
esac                                                                                                                                                                                                                                  
exit 0     