#!/bin/bash

export ESCIDOCNG_SERVER_HOME=/data/escidoc-ng/server
export ESCIDOCNG_SERVER_NAME=escidoc-ng-server
export ESCIDOCNG_FRONTEND_HOME=/data/escidoc-ng/frontend
export ESCIDOCNG_FRONTEND_NAME=escidoc-ng-frontend

#Names of startscripts. Has to be located in ESCIDOCNG_SERVER_HOME + ESCIDOCNG_FRONTEND_HOME
export ESCIDOCNG_SERVER_STARTSCRIPT=server.start
export ESCIDOCNG_FRONTEND_STARTSCRIPT=frontend.start

export ESCIDOCNG_USER=admin

function start {
    if pkill -0 -f $ESCIDOCNG_SERVER_NAME.jar > /dev/null 2>&1
    then
    	pkill -f $ESCIDOCNG_SERVER_NAME.jar > /dev/null 2>&1
    fi
    echo "Starting server..."
    cd $ESCIDOCNG_SERVER_HOME
    sudo -u $ESCIDOCNG_USER ./$ESCIDOCNG_SERVER_STARTSCRIPT
    
    sleep 30
    
    if pkill -0 -f $ESCIDOCNG_FRONTEND_NAME.jar > /dev/null 2>&1
    then
        pkill -f $ESCIDOCNG_FRONTEND_NAME.jar > /dev/null 2>&1
    fi
    echo "Starting frontend..."
    cd $ESCIDOCNG_FRONTEND_HOME
    sudo -u $ESCIDOCNG_USER ./$ESCIDOCNG_FRONTEND_STARTSCRIPT 
}

function stop {
    if ! pkill -0 -f $ESCIDOCNG_SERVER_NAME.jar > /dev/null 2>&1
    then
        echo "Service [$ESCIDOCNG_SERVER_NAME] is not running. Ignoring shutdown request."
    else
    	pkill -f $ESCIDOCNG_SERVER_NAME.jar > /dev/null 2>&1
    fi

    if ! pkill -0 -f $ESCIDOCNG_FRONTEND_NAME.jar > /dev/null 2>&1
    then
        echo "Service [$ESCIDOCNG_FRONTEND_NAME] is not running. Ignoring shutdown request."
    else
    	pkill -f $ESCIDOCNG_FRONTEND_NAME.jar > /dev/null 2>&1
    fi
    
}

case $1 in
start)
    start
;;
stop)
    stop
;;
restart)
    stop
    start
;;
esac                                                                                                                                                                                                                                  
exit 0     